# General Jekyll Config
url: https://alyssamiao.github.io/
safe: true
lsi: false
exclude: [CNAME]
kramdown:
  input: GFM
  hard_wrap: false
poole:
  default_layout: post
gems:
  - jekyll-redirect-from
excerpt_separator: <!--more-->
